services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8081:80" # Expose WordPress on port 8081
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html 
      - ./wordpress_code:/var/www/html 

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data:/var/lib/mysql # Persist database data

volumes:
  wordpress_data:
  wordpress_code:
  db_data: